---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  sqlite3
  database: merb_auth_slice_fullfat_development.db
  username: root
  password: 
  host: localhost
  socket: "/tmp/mysql.sock"
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: merb_auth_slice_fullfat_test.db
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: merb_auth_slice_fullfat.db
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults